### ISSUE TITLE
Dataset dir

### ISSUE THREAD

**Issue by oisonan1999** [Iretha/IoT-23-anomaly-detection#6]
Hi!
I am researching your project and I have a problem in the config.py files.
I see you have the path iot23_scenarios_dir but in the dataset I downloaded on the website https://www.stratosphereips.org/datasets-iot23 there is only the path opt\Malware-Project\BigDataset\IoTScenarios\CTU-Honeypot-Capture-.......
So I can't continue. Can you show me the exact directory path? Thank you so much

**Comment by RaffaeleBarbato** [comment]
@oisonan1999 probably you have downloaded the full dataset, but this work is focusing on the lightweight version, containing only the labeled flows without the pcaps files (8.8 GB).

**Comment by Iretha** [comment]
> 
> 
> Hi! I am researching your project and I have a problem in the config.py files. I see you have the path iot23_scenarios_dir but in the dataset I downloaded on the website https://www.stratosphereips.org/datasets-iot23 there is only the path opt\Malware-Project\BigDataset\IoTScenarios\CTU-Honeypot-Capture-....... So I can't continue. Can you show me the exact directory path? Thank you so much

Current project works with [https://mcfp.felk.cvut.cz/publicDatasets/IoT-23-Dataset/iot_23_datasets_small.tar.gz](https://mcfp.felk.cvut.cz/publicDatasets/IoT-23-Dataset/iot_23_datasets_small.tar.gz) from [https://www.stratosphereips.org/datasets-iot23](https://www.stratosphereips.org/datasets-iot23).
